@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

object WishlistPlatform
object User
object Wishlist
object Wish




WishlistPlatform *-- User
User *-- Wishlist
Wishlist *-- Wish


@enduml